# Generated by Django 5.0.6 on 2024-06-08 18:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("text_gen", "0002_alter_chatsession_content_chatuser_chatsession_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatsession",
            name="users",
        ),
    ]
