# Generated by Django 5.0.6 on 2024-06-08 18:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("text_gen", "0003_remove_chatsession_users"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chatsession",
            name="session",
        ),
        migrations.AddField(
            model_name="chatsession",
            name="session_name",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
