# Generated by Django 5.0.6 on 2024-06-08 19:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("text_gen", "0004_remove_chatsession_session_chatsession_session_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatsession",
            name="content",
            field=models.JSONField(default=1),
            preserve_default=False,
        ),
    ]
