# Generated by Django 5.0.6 on 2024-06-08 19:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("text_gen", "0007_alter_chatsession_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatsession",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
