# Generated by Django 5.0.6 on 2024-06-19 20:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("note", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="note",
            old_name="field_name",
            new_name="content",
        ),
        migrations.RenameField(
            model_name="noteuser",
            old_name="date_added",
            new_name="created_date",
        ),
    ]
